(function(){
'use strict';

const CREDO_TRANSLATIONS = {
  en: {
    levels:{'初級':'Beginner','中級':'Intermediate','上級':'Advanced','超上級':'Expert'},
    chapters:{
      'Day 1｜クレド全体を理解する':'Day 1 | Understanding the Credo as a whole',
      'Day 2｜クレド④〜⑥':'Day 2 | Credo 4–6',
      'Day 3｜行動からクレドを逆引きする':'Day 3 | Working backward from actions to the Credo',
      'Day 4｜一見クレドっぽいけどズレている':'Day 4 | Looks like the Credo, but is off',
      'Day 5｜似ているクレドの違いを見抜く':'Day 5 | Distinguishing similar Credo ideas'
    },
    credo:{
      '4つの経営品質':'Four Management Qualities',
      '4つの経営品質｜顧客本位':'Four Management Qualities | Customer Focus',
      '4つの経営品質｜社員重視':'Four Management Qualities | Employee Focus',
      '4つの経営品質｜独自能力':'Four Management Qualities | Unique Capabilities',
      '顧客本位＋行動指針Ⅱ｜手を差し伸べ、つなぐ':'Customer Focus + Guideline II | Reach out and connect',
      '行動指針Ⅲ｜勇気をもって、かえる':'Guideline III | Have the courage to change',
      '行動指針Ⅲ｜勇気をもって、かえる':'Guideline III | Have the courage to change',
      '社員重視＋独自能力':'Employee Focus + Unique Capabilities',
      '独自能力':'Unique Capabilities',
      '独自能力＋行動指針Ⅲ｜勇気をもって、かえる':'Unique Capabilities + Guideline III | Have the courage to change',
      '社員重視＋独自能力':'Employee Focus + Unique Capabilities',
      '独自能力＋行動指針Ⅳ｜支え、伝え、分かち合う':'Unique Capabilities + Guideline IV | Support, pass on, and share',
      '行動指針Ⅱ｜手を差し伸べ、つなぐ':'Guideline II | Reach out and connect',
      '行動指針Ⅳ｜支え、伝え、分かち合う':'Guideline IV | Support, pass on, and share',
      '顧客本位':'Customer Focus',
      '行動指針Ⅱ＋顧客本位':'Guideline II + Customer Focus',
      '顧客本位＋独自能力＋行動指針Ⅲ＋行動指針Ⅳ':'Customer Focus + Unique Capabilities + Guidelines III & IV'
    },
    q:[
      {q:'Which of the following is NOT included in Hogetsu Credo’s “Four Management Qualities”?',s:'Let’s recall the four management qualities.',c:['Customer Focus','Employee Focus','Business Results Focus','Unique Capabilities'],e:'The four management qualities are Customer Focus, Employee Focus, Unique Capabilities, and Harmony with Society. “Business Results Focus” is not one of the four.'},
      {q:'Which is closest to the explanation of “Customer Focus” in the materials?',s:'The key is how we understand “the customer comes first.”',c:['Provide what customers request accurately and quickly.','Prioritize increasing sales and profit, and improve customer satisfaction for that purpose.','Explore the value customers truly seek and provide value that leads to satisfaction.','Do our best to meet every customer request and never say no.'],e:'Customer Focus is not simply providing whatever is requested. It means exploring what customers truly need and considering the value that is genuinely useful to them.'},
      {q:'A situation arises where someone thinks, “My part is finished, so the next person will figure it out.” Which action is closest to the Hogetsu Credo?',s:'You are handing work to the next process.',c:['Pass it to the next process as-is because your work is finished.','Check the information and points to watch so the next person can work without trouble.','Take over the next person’s work as well.','Wait until the next person asks a question, then respond.'],e:'People in the next process are also indirect customers. It is important to hand work over in a state that makes it easier for the next person to continue. This is different from taking everything on yourself.'},
      {q:'You are told, “Do it the same way as last year,” but something about the method feels slightly wrong. Which is closest to the Credo?',s:'Think about how to handle precedent.',c:['There is a precedent, so do exactly what was done last year.','Respect the precedent while asking, “Could this be done better?”','Change it on your own because your way seems better.','Ignore the discomfort because changing it is a hassle.'],e:'The point is not to reject precedent, but to appreciate it, question it, and think about a better way.'},
      {q:'Which is closest to the Credo’s idea of “Employee Focus”?',s:'What does it mean to value employees?',c:['Reduce employees’ workload as much as possible so they can enjoy working.','Create opportunities and an environment for employees to learn, take on challenges, and develop their abilities.','Prioritize everything employees want over company policy.','Make getting along with each other the top priority.'],e:'Employee Focus means creating systems and opportunities that bring out motivation and ability, while investing in learning and growth.'},
      {q:'An employee wants to take on new work but is afraid of failure and only wants to use methods they already know. Which response best reflects both Employee Focus and Unique Capabilities?',s:'A situation where a person wants to challenge themselves but also feels anxious.',c:['Keep assigning the same work because failure would cause problems.','Respect the employee’s wishes and let them do anything in any way they choose.','Respect the desire to challenge while providing learning and support that enables a new challenge.','Ask them to prove they can succeed alone before trying anything new.'],e:'Employee Focus means providing opportunities and support for growth. Unique Capabilities values flexibility, willingness to challenge, and originality. Creating an environment that supports challenge is important.'},
      {q:'Someone says, “We have always done this task this way, and there are no problems, so there is no need to change.” Which is closest to the Credo?',s:'The process seems fine as it is.',c:['If there are no problems, keep it as it is.','Precedents have meaning, so they should not be changed.','Respect the precedent while considering whether there is truly a better way.','Trying a new method matters in itself, so change it immediately.'],e:'The point is neither to protect precedent unconditionally nor to change it without reason, but to understand its meaning and consider a better approach.'},
      {q:'Which is closest to the idea of “Unique Capabilities”?',s:'How do we create strengths that are uniquely ours?',c:['Adopt successful examples from other companies as closely as possible.','Repeat existing work accurately and consistently.','Use flexibility, willingness to challenge, and originality to create strengths unique to our company.','Accept every customer request and expand the range of services.'],e:'Unique Capabilities means aiming to become a truly distinctive company by valuing flexibility, a spirit of challenge, and originality.'},
      {q:'An employee wants to use a new tool to improve efficiency but is afraid of failure, so they try it alone without consulting anyone. Which response is closest to the Credo?',s:'The environment that supports a challenge also matters.',c:['They are inexperienced, so do not let them try new things.','Respect their motivation and let them work completely alone.','Respect the willingness to challenge while creating an environment where they can learn and get support as they try it.','To prevent failure, make them use the old method instead.'],e:'Employee Focus creates opportunities and systems that bring out motivation and ability, while Unique Capabilities values a spirit of challenge. The goal is to support challenges rather than make someone carry them alone.'},
      {q:'Someone says, “This work has always been done this way, so there is no need to change it.” Which response is most appropriate?',s:'Balance respecting precedent with improvement.',c:['Respect the senior employee’s experience and continue as before.','If you think it is inefficient, immediately switch to a new method.','Understand why the current method exists, then think about a better way while considering its purpose.','Try a new method alone and tell others after you get results.'],e:'The point is to appreciate precedent, question it, and have dialogue about the future. It is neither simply preserving the old method nor changing it on your own.'},
      {q:'An employee greatly improved efficiency and thinks, “I developed this method, so I don’t want to teach anyone else. If only I can do it, my value will rise.” Which is closest to the Credo?',s:'Can an individual strength become an organizational strength?',c:['It is a Unique Capability, so it should remain their personal technique.','The result is good, so there is no problem if only they can use it.','A unique idea can be a strength, but sharing the know-how can also turn it into organizational capability.','Because they created it, they do not need to share it with the company.'],e:'It is important not only to create unique improvements, but also to pass on and share experience and know-how so they become a strength of the organization.'},
      {q:'A colleague asks for help with work. Even though you are busy, you think, “First I should hear what they are struggling with, and help where I can.” Which is closest?',s:'Supporting a colleague who is having trouble.',c:['Customer Focus','Bonds built together with colleagues','Have the courage to change for a better society','Turn pride in our work and know-how into value'],e:'Guideline II is about reaching out and connecting. The focus here is helping a colleague who is struggling now and helping them move forward.'},
      {q:'You are thinking, “I should keep my process-improvement method to myself so only I can use it.” Which action guideline is most closely related?',s:'How should you handle your own improvement idea?',c:['For the future of customers, listen, speak, and understand thoroughly.','For the bonds we build together, reach out and connect.','For a better society, have the courage to change.','To turn pride in our work and know-how into value, support, pass on, and share.'],e:'Instead of keeping your method to yourself, sharing and passing it on as know-how directly connects to “Support, pass on, and share.”'},
      {q:'A customer asks, “Can you move up the delivery date?” Instead of immediately saying yes, you decide to ask, “Why is that date necessary?” and “What are you really struggling with?” Which connects most directly?',s:'Look for the real need behind the request.',c:['Customer Focus','Employee Focus','Unique Capabilities','Harmony with Society'],e:'Customer Focus means not simply accepting the stated request, but exploring what the customer is really seeking and considering the value that matters.'},
      {q:'A colleague in the next process will use a document you created. You organize the information so they can easily see what they need. Which is most directly connected?',s:'Handing work to someone in the next process.',c:['Customer Focus','Bonds built together with colleagues','Have the courage to change for a better society','Turn pride in our work and know-how into value'],e:'Even when the recipient is a colleague, supporting the next process and connecting the work directly relates to the bonds built together with colleagues. Because the next process is also an indirect customer, Customer Focus is included too.'},
      {q:'You are handing over work you have handled for years. Instead of only giving the procedure, you explain why it is done this way and what mistakes happened in the past so the successor can make decisions independently. What is the most direct fit?',s:'A handover that connects experience and knowledge to the next person.',c:['Bonds built together with colleagues','Turn pride in our work and know-how into value','Customer Focus','Unique Capabilities'],e:'The focus is not just helping someone who is in trouble now, but leaving your knowledge, experience, and mistakes as useful value for the next person. That most directly fits turning know-how into value.'},
      {q:'You have a new process-improvement idea. You confirm the real problem at the workplace, understand why the current method exists, try a better method, and share it so others can use it. Which approach is closest?',s:'Link several Credo ideas through one piece of work.',c:['Run the new method first → share it after success → ask the workplace for opinions.','Listen to the workplace → understand why the current method exists → think of and test a better method → share it in a usable form.','Explain it to a manager → execute after approval → produce results alone → get evaluated.','Check whether the current method has a problem → do not change it if not → improve only when needed.'],e:'The flow connects listening, understanding, challenging, and sharing—Customer Focus, how we face precedent, Unique Capabilities, and sharing know-how.'},
      {q:'A representative receives a very difficult customer request and says, “It’s customer first, so we should accept everything no matter what.” Which is closest?',s:'The key is how we understand “customer first.”',c:['Correct. Customer Focus means accepting every customer request.','Basically correct. If the customer is satisfied, internal burden should come later.','Not quite. Customer Focus means thinking about what is genuinely valuable to the customer, not simply accepting the request as stated.','Wrong. Customer Focus means prioritizing our own profit and responding within that range.'],e:'Customer Focus does not mean accepting every request unconditionally. It means thinking about what is genuinely valuable to the other party and, when appropriate, making a different proposal.'},
      {q:'Seeing a busy colleague, someone says, “The Credo says we help our teammates, so I’ll take over all of their work.” Which is closest?',s:'The difference between reaching out and taking everything on yourself.',c:['Correct. For a colleague’s sake, you should take everything on even if your own workload increases.','Basically correct. Helping means finishing the work quickly.','Not quite. Reaching out can mean supporting the person so they can move forward themselves, or connecting them with the right person or information.','Wrong. Do not get involved in colleagues’ work; just do your own.'],e:'Helping a colleague does not mean doing everything in their place. It is important to support them so they can move forward and connect them with the people and information they need.'},
      {q:'Someone says, “It is important to challenge precedent,” and changes the current workflow drastically without checking anything. Which is most appropriate?',s:'“Challenge” and “changing things without consultation” are not the same.',c:['Correct. Trying something new automatically aligns with the Credo.','Correct. Since questioning precedent is important, no confirmation is needed.','Not quite. Questioning precedent matters, but it is important to understand the reason and think about a better way through dialogue.','Wrong. Precedents should basically never be changed.'],e:'The point is to appreciate precedent, question it, and have dialogue about the future. Do not change something just because it is new; act to make it better.'},
      {q:'An employee teaches a junior their work know-how but thinks, “If I teach everything, I lose my value, so I won’t teach the key tips.” Which is closest?',s:'The difference between “passing it on” and “keeping it only for yourself.”',c:['No problem. Protecting your own value is also important.','Sharing only the basics is enough.','It is important to pass on know-how and experience so successors can use them, carrying the value of the work forward.','Juniors should think for themselves, so there is no need to teach even the basics.'],e:'It is important to build a culture of passing on know-how and sharing information, turning Hogetsu’s strengths from something that merely exists into something others can use.'},
      {q:'Which of these four actions looks good at first, but is actually off from the Credo?',s:'Compare the four actions.',c:['Listen to the customer, confirm the background, and then make a proposal.','Take over all of a busy junior employee’s work and finish it without letting them do anything.','Confirm why an inefficient process exists and discuss an improvement with everyone.','Turn a useful method you discovered into a procedure and share it with a junior.'],e:'B may look kind, but supporting a colleague is not the same as taking all of their work away. The goal is to support and connect so the person can move forward.'},
      {q:'A junior who is struggling with work for the first time is told, “Here is how to think about this, and here is who you should ask in this situation,” while working together. What is the closest direct fit?',s:'Are you helping a colleague right now, or leaving experience behind?',c:['Bonds built together with colleagues','Turn pride in our work and know-how into value','Unique Capabilities','Customer Focus'],e:'The main focus is reaching out to a colleague who is struggling now and moving forward together. When it also includes passing on know-how, it connects to turning know-how into value as well.'},
      {q:'When handing your document to a colleague in the next process, you organize it and say, “Follow this order and it will make sense; be careful here.” Which is the closest direct fit?',s:'The next process can also be considered a “customer.”',c:['Customer Focus','Bonds built together with colleagues','Unique Capabilities','Harmony with Society'],e:'People in the next process can be considered indirect customers. Here, the focus is delivering the information in a state that creates value for the recipient, so Customer Focus is central.'},
      {q:'After years of doing a job, you hand it over to a junior. You want to share not only the procedure, but why it is done this way and what mistakes happened in the past, so they can make decisions themselves. What is the most direct fit?',s:'A handover that connects experience and knowledge.',c:['Bonds built together with colleagues','Turn pride in our work and know-how into value','Customer Focus','Unique Capabilities'],e:'The center of the action is leaving knowledge, experience, and past mistakes as useful value for the next person—not just helping someone in the moment—so it most directly fits turning know-how into value.'},
      {q:'You found a new way of working and think, “Let’s organize it so other departments can use it too.” What is more central?',s:'The difference between creating a new method and leaving it in a usable form.',c:['Unique Capabilities','Turn pride in our work and know-how into value','Bonds built together with colleagues','Customer Focus'],e:'Creating a new method is Unique Capabilities, but here the main action is making it usable by other departments, so turning know-how into value is more direct.'},
      {q:'A junior asks, “Why do we do it this way?” After teaching the procedure, you explain, “We had this mistake before, so we chose this method to prevent it,” sharing the background as well. Which Credo is strongest here?',s:'Leave not only the method, but the experience behind it.',c:['Unique Capabilities','Bonds built together with colleagues','Turn pride in our work and know-how into value','Customer Focus'],e:'More than creating a new method, the key is sharing why the method exists and the past experience and mistakes behind it in a way the next person can use. That most strongly reflects turning know-how into value.'},
      {q:'After creating a process-improvement tool, you think, “Let’s make a manual so everyone can use it easily. Along with how to operate it, let’s leave what problem it solves and why we chose these specifications.” Which Credo is central?',s:'Focus on leaving the “why,” not only the fact that it was created.',c:['Unique Capabilities','Bonds built together with colleagues','Turn pride in our work and know-how into value','Customer Focus'],e:'Creating the tool itself involves Unique Capabilities, but the main point here is leaving the problem and the background behind the specifications so future users can use that experience and judgment as value.'}
    ]
  },
  vi: {
    levels:{'初級':'Cơ bản','中級':'Trung cấp','上級':'Nâng cao','超上級':'Chuyên gia'},
    chapters:{
      'Day 1｜クレド全体を理解する':'Ngày 1 | Hiểu tổng thể về Credo',
      'Day 2｜クレド④〜⑥':'Ngày 2 | Credo 4–6',
      'Day 3｜行動からクレドを逆引きする':'Ngày 3 | Từ hành động để nhận ra Credo',
      'Day 4｜一見クレドっぽいけどズレている':'Ngày 4 | Trông giống Credo nhưng chưa đúng',
      'Day 5｜似ているクレドの違いを見抜く':'Ngày 5 | Nhận ra sự khác nhau giữa các Credo gần giống nhau'
    },
    credo:{
      '4つの経営品質':'4 phẩm chất quản trị',
      '4つの経営品質｜顧客本位':'4 phẩm chất quản trị | Lấy khách hàng làm trọng tâm',
      '4つの経営品質｜社員重視':'4 phẩm chất quản trị | Lấy nhân viên làm trọng tâm',
      '4つの経営品質｜独自能力':'4 phẩm chất quản trị | Năng lực khác biệt',
      '顧客本位＋行動指針Ⅱ｜手を差し伸べ、つなぐ':'Lấy khách hàng làm trọng tâm + Nguyên tắc II | Chủ động giúp đỡ và kết nối',
      '行動指針Ⅲ｜勇気をもって、かえる':'Nguyên tắc III | Dũng cảm thay đổi',
      '社員重視＋独自能力':'Lấy nhân viên làm trọng tâm + Năng lực khác biệt',
      '独自能力':'Năng lực khác biệt',
      '独自能力＋行動指針Ⅲ｜勇気をもって、かえる':'Năng lực khác biệt + Nguyên tắc III | Dũng cảm thay đổi',
      '独自能力＋行動指針Ⅳ｜支え、伝え、分かち合う':'Năng lực khác biệt + Nguyên tắc IV | Hỗ trợ, truyền đạt và chia sẻ',
      '行動指針Ⅱ｜手を差し伸べ、つなぐ':'Nguyên tắc II | Chủ động giúp đỡ và kết nối',
      '行動指針Ⅳ｜支え、伝え、分かち合う':'Nguyên tắc IV | Hỗ trợ, truyền đạt và chia sẻ',
      '顧客本位':'Lấy khách hàng làm trọng tâm',
      '行動指針Ⅱ＋顧客本位':'Nguyên tắc II + Lấy khách hàng làm trọng tâm',
      '顧客本位＋独自能力＋行動指針Ⅲ＋行動指針Ⅳ':'Lấy khách hàng làm trọng tâm + Năng lực khác biệt + Nguyên tắc III & IV'
    },
    q:[
      {q:'Nội dung nào sau đây KHÔNG thuộc “4 phẩm chất quản trị” của Hogetsu Credo?',s:'Hãy nhớ lại 4 phẩm chất quản trị.',c:['Lấy khách hàng làm trọng tâm','Lấy nhân viên làm trọng tâm','Tập trung vào kết quả kinh doanh','Năng lực khác biệt'],e:'4 phẩm chất quản trị là Lấy khách hàng làm trọng tâm, Lấy nhân viên làm trọng tâm, Năng lực khác biệt và Hài hòa với xã hội. “Tập trung vào kết quả kinh doanh” không nằm trong 4 phẩm chất này.'},
      {q:'Điều nào gần nhất với phần giải thích về “Lấy khách hàng làm trọng tâm” trong tài liệu?',s:'Điểm quan trọng là cách chúng ta hiểu “khách hàng là trên hết”.',c:['Cung cấp chính xác và nhanh chóng những gì khách hàng yêu cầu.','Ưu tiên tăng doanh thu và lợi nhuận, vì vậy nâng cao sự hài lòng của khách hàng.','Tìm hiểu giá trị mà khách hàng thực sự mong muốn và cung cấp giá trị tạo nên sự hài lòng.','Cố gắng đáp ứng mọi yêu cầu của khách hàng và không từ chối.'],e:'Lấy khách hàng làm trọng tâm không chỉ là cung cấp mọi thứ được yêu cầu. Đó là việc tìm hiểu điều khách hàng thực sự cần và cân nhắc giá trị thực sự hữu ích cho họ.'},
      {q:'Có người nghĩ: “Phần việc của tôi đã xong, người tiếp theo sẽ tự xử lý.” Hành động nào gần với Credo nhất?',s:'Bạn đang bàn giao công việc cho công đoạn tiếp theo.',c:['Bàn giao nguyên trạng vì phần việc của mình đã xong.','Kiểm tra thông tin và điểm cần lưu ý để người tiếp theo có thể làm việc thuận lợi.','Nhận luôn cả công việc của người tiếp theo.','Chờ người tiếp theo hỏi rồi mới trả lời.'],e:'Người ở công đoạn tiếp theo cũng có thể được xem là khách hàng gián tiếp. Điều quan trọng là bàn giao ở trạng thái giúp người tiếp theo dễ làm việc, chứ không phải tự ôm hết mọi việc.'},
      {q:'Bạn được nói: “Hãy làm giống năm ngoái”, nhưng cảm thấy cách làm có chút không ổn. Cách nào gần với Credo nhất?',s:'Hãy suy nghĩ về cách tiếp cận tiền lệ.',c:['Có tiền lệ nên cứ làm y như năm ngoái.','Tôn trọng tiền lệ nhưng tự hỏi: “Có thể làm tốt hơn không?”','Tự ý thay đổi vì cách của mình có vẻ tốt hơn.','Bỏ qua cảm giác đó vì thay đổi rất phiền.'],e:'Điểm quan trọng không phải phủ nhận tiền lệ mà là trân trọng, đặt câu hỏi và suy nghĩ về cách tốt hơn.'},
      {q:'Điều nào gần nhất với cách hiểu về “Lấy nhân viên làm trọng tâm”?',s:'“Coi trọng nhân viên” có nghĩa gì?',c:['Giảm tối đa khối lượng công việc để nhân viên làm việc vui vẻ.','Tạo cơ hội và môi trường để nhân viên học hỏi, thử thách và phát huy năng lực.','Ưu tiên mọi mong muốn của nhân viên hơn chính sách công ty.','Đặt việc mọi người hòa thuận lên trên hết.'],e:'Lấy nhân viên làm trọng tâm là tạo ra cơ chế và cơ hội để phát huy động lực và năng lực, đồng thời đầu tư cho việc học hỏi và phát triển.'},
      {q:'Một nhân viên muốn thử công việc mới nhưng sợ thất bại nên chỉ muốn dùng cách đã biết. Cách nào phù hợp nhất với cả “Lấy nhân viên làm trọng tâm” và “Năng lực khác biệt”?',s:'Một tình huống vừa muốn thử thách vừa lo lắng.',c:['Tiếp tục giao việc cũ vì thất bại sẽ gây rắc rối.','Tôn trọng mong muốn và để họ tự do làm theo bất kỳ cách nào.','Tôn trọng mong muốn thử thách, đồng thời chuẩn bị cơ hội học hỏi và hỗ trợ để thử cách mới.','Yêu cầu họ chứng minh rằng có thể thành công một mình trước.'],e:'Lấy nhân viên làm trọng tâm là tạo cơ hội và hỗ trợ để phát triển. Năng lực khác biệt coi trọng sự linh hoạt, tinh thần thử thách và tính sáng tạo.'},
      {q:'Có người nói: “Công việc này trước giờ vẫn làm như vậy, không có vấn đề gì nên không cần thay đổi.” Cách nào gần với Credo nhất?',s:'Quy trình có vẻ ổn như hiện tại.',c:['Không có vấn đề thì cứ giữ nguyên.','Tiền lệ có ý nghĩa nên không nên thay đổi.','Tôn trọng tiền lệ và đồng thời xem có thực sự có cách tốt hơn hay không.','Việc thử cách mới quan trọng nên thay đổi ngay.'],e:'Điểm quan trọng là không mù quáng giữ tiền lệ cũng không thay đổi vô lý, mà hiểu ý nghĩa của cách cũ rồi nghĩ đến phương án tốt hơn.'},
      {q:'Điều nào gần nhất với “Năng lực khác biệt”?',s:'Làm thế nào tạo ra thế mạnh riêng của công ty?',c:['Áp dụng thành công của công ty khác càng giống càng tốt.','Lặp lại công việc hiện có chính xác và ổn định.','Phát huy sự linh hoạt, tinh thần thử thách và tính sáng tạo để tạo nên thế mạnh riêng của công ty.','Chấp nhận mọi yêu cầu của khách hàng và mở rộng phạm vi đáp ứng.'],e:'Năng lực khác biệt hướng tới việc trở thành doanh nghiệp có nét riêng, coi trọng sự linh hoạt, tinh thần thử thách và tính sáng tạo.'},
      {q:'Một nhân viên muốn dùng công cụ mới để tăng hiệu quả nhưng sợ thất bại nên tự thử một mình mà không hỏi ai. Cách nào gần với Credo nhất?',s:'Môi trường hỗ trợ thử thách cũng rất quan trọng.',c:['Vì còn ít kinh nghiệm nên không cho thử điều mới.','Tôn trọng động lực và để họ hoàn toàn tự làm.','Tôn trọng ý chí thử thách và tạo môi trường để họ học hỏi, nhận hỗ trợ khi thử.','Để tránh thất bại, bắt họ dùng cách cũ.'],e:'Lấy nhân viên làm trọng tâm tạo cơ hội và cơ chế để phát huy động lực, còn Năng lực khác biệt coi trọng tinh thần thử thách. Mục tiêu là hỗ trợ thử thách thay vì để một người tự gánh.'},
      {q:'Có người nói: “Công việc này trước giờ vẫn làm vậy, nên không cần thay đổi.” Cách phản hồi nào phù hợp nhất?',s:'Cân bằng giữa tôn trọng tiền lệ và cải tiến.',c:['Tôn trọng kinh nghiệm của người đi trước và tiếp tục như cũ.','Nếu thấy kém hiệu quả thì đổi ngay sang cách mới.','Hiểu vì sao cách hiện tại được dùng, rồi cùng suy nghĩ cách tốt hơn.','Tự thử cách mới và chỉ báo cho mọi người sau khi có kết quả.'],e:'Điểm quan trọng là trân trọng tiền lệ, đặt câu hỏi và đối thoại hướng tới tương lai. Không phải chỉ giữ cách cũ hoặc tự ý đổi.'},
      {q:'Một nhân viên cải tiến công việc rất hiệu quả và nghĩ: “Đây là cách tôi nghĩ ra nên không muốn dạy ai. Nếu chỉ mình tôi làm được thì giá trị của tôi sẽ tăng.” Cách nào gần với Credo?',s:'Có thể biến thế mạnh cá nhân thành thế mạnh của tổ chức không?',c:['Đó là Năng lực khác biệt nên nên giữ làm kỹ thuật riêng.','Kết quả tốt nên chỉ mình họ dùng cũng không sao.','Ý tưởng riêng có thể là thế mạnh, nhưng chia sẻ bí quyết cũng rất quan trọng để biến nó thành sức mạnh của tổ chức.','Vì họ tạo ra nên không cần chia sẻ với công ty.'],e:'Không chỉ tạo ra cải tiến riêng, mà còn cần truyền đạt và chia sẻ kinh nghiệm, bí quyết để chúng trở thành sức mạnh chung của tổ chức.'},
      {q:'Đồng nghiệp nhờ bạn giúp việc. Dù đang bận, bạn nghĩ: “Trước tiên hãy nghe xem họ đang gặp khó khăn gì, rồi hỗ trợ khi cần.” Hành động này gần nhất với điều nào?',s:'Hỗ trợ một đồng đội đang gặp khó khăn.',c:['Lấy khách hàng làm trọng tâm','Mối gắn kết được xây dựng cùng đồng đội','Dũng cảm thay đổi vì một xã hội tốt đẹp hơn','Biến niềm tự hào trong công việc và bí quyết thành giá trị'],e:'Nguyên tắc II nói về việc chủ động giúp đỡ và kết nối. Trọng tâm ở đây là hỗ trợ đồng đội đang gặp khó khăn và giúp họ tiến lên.'},
      {q:'Bạn nghĩ: “Hãy giữ cách cải tiến công việc cho riêng mình để chỉ mình sử dụng.” Nguyên tắc hành động nào liên quan nhất?',s:'Bạn nên xử lý ý tưởng cải tiến của mình như thế nào?',c:['Vì tương lai khách hàng, lắng nghe, diễn đạt và thấu hiểu triệt để.','Vì mối gắn kết cùng đồng đội, chủ động giúp đỡ và kết nối.','Vì một xã hội tốt đẹp hơn, dũng cảm thay đổi.','Để biến niềm tự hào trong công việc và bí quyết thành giá trị, hãy hỗ trợ, truyền đạt và chia sẻ.'],e:'Không giữ phương pháp cho riêng mình mà truyền đạt, chia sẻ như một bí quyết sẽ trực tiếp gắn với “Hỗ trợ, truyền đạt và chia sẻ”.'},
      {q:'Khách hàng hỏi: “Có thể giao hàng sớm hơn không?” Thay vì lập tức nói “được”, bạn hỏi: “Vì sao cần ngày đó?” và “Thực sự đang gặp khó khăn gì?” Điều nào liên quan trực tiếp nhất?',s:'Tìm nhu cầu thực sự phía sau yêu cầu.',c:['Lấy khách hàng làm trọng tâm','Lấy nhân viên làm trọng tâm','Năng lực khác biệt','Hài hòa với xã hội'],e:'Lấy khách hàng làm trọng tâm nghĩa là không chỉ nhận yêu cầu được nói ra, mà tìm hiểu điều khách hàng thực sự cần và giá trị quan trọng với họ.'},
      {q:'Một đồng nghiệp ở công đoạn tiếp theo sẽ sử dụng tài liệu bạn tạo. Bạn sắp xếp thông tin để họ dễ tìm nội dung cần thiết. Điều nào liên quan trực tiếp nhất?',s:'Bàn giao công việc cho người ở công đoạn tiếp theo.',c:['Lấy khách hàng làm trọng tâm','Mối gắn kết được xây dựng cùng đồng đội','Dũng cảm thay đổi vì một xã hội tốt đẹp hơn','Biến niềm tự hào trong công việc và bí quyết thành giá trị'],e:'Ngay cả khi người nhận là đồng nghiệp, việc hỗ trợ công đoạn tiếp theo và kết nối công việc liên quan trực tiếp đến mối gắn kết cùng đồng đội. Vì công đoạn sau cũng là “khách hàng” gián tiếp nên có cả góc nhìn lấy khách hàng làm trọng tâm.'},
      {q:'Bạn bàn giao công việc đã phụ trách nhiều năm. Không chỉ đưa quy trình, bạn còn giải thích vì sao làm như vậy và những sai sót từng xảy ra để người nhận có thể tự quyết định sau này. Điều nào trực tiếp nhất?',s:'Bàn giao kinh nghiệm và kiến thức cho người tiếp theo.',c:['Mối gắn kết được xây dựng cùng đồng đội','Biến niềm tự hào trong công việc và bí quyết thành giá trị','Lấy khách hàng làm trọng tâm','Năng lực khác biệt'],e:'Trọng tâm là để lại kiến thức, kinh nghiệm và cả sai sót trong quá khứ như một giá trị hữu ích cho người tiếp theo, nên phù hợp trực tiếp nhất với việc biến bí quyết thành giá trị.'},
      {q:'Bạn có ý tưởng cải tiến công việc mới. Bạn xác nhận vấn đề thực sự ở hiện trường, hiểu vì sao cách hiện tại tồn tại, thử cách tốt hơn và chia sẻ để người khác có thể sử dụng. Cách tiến hành nào gần nhất?',s:'Kết nối nhiều Credo trong một công việc.',c:['Thực hiện cách mới → thành công rồi chia sẻ → hỏi ý kiến hiện trường.','Lắng nghe hiện trường → hiểu vì sao cách hiện tại tồn tại → nghĩ và thử cách tốt hơn → chia sẻ dưới dạng dễ sử dụng.','Giải thích với cấp trên → được duyệt rồi làm → tự tạo kết quả → được đánh giá.','Kiểm tra xem cách hiện tại có vấn đề không → không có thì không đổi → chỉ cải tiến khi cần.'],e:'Quy trình kết nối lắng nghe, thấu hiểu, thử thách và chia sẻ—lấy khách hàng làm trọng tâm, cách đối diện với tiền lệ, năng lực khác biệt và chia sẻ bí quyết.'},
      {q:'Một nhân viên nhận yêu cầu rất khó từ khách hàng và nói: “Khách hàng là trên hết nên phải nhận tất cả bằng mọi giá.” Điều nào gần nhất?',s:'Điểm quan trọng là hiểu đúng “khách hàng là trên hết”.',c:['Đúng. Lấy khách hàng làm trọng tâm nghĩa là chấp nhận mọi yêu cầu.','Về cơ bản đúng. Nếu khách hàng hài lòng thì gánh nặng nội bộ có thể để sau.','Chưa hẳn. Lấy khách hàng làm trọng tâm là suy nghĩ giá trị thực sự cho khách hàng, không phải chỉ nhận yêu cầu như đã nói.','Sai. Lấy khách hàng làm trọng tâm là ưu tiên lợi nhuận của công ty trong phạm vi đó.'],e:'Lấy khách hàng làm trọng tâm không có nghĩa chấp nhận mọi yêu cầu vô điều kiện. Điều quan trọng là suy nghĩ điều thực sự có giá trị cho đối phương và khi cần đưa ra đề xuất khác.'},
      {q:'Thấy đồng nghiệp bận, một người nói: “Credo bảo phải giúp đồng đội, nên tôi sẽ làm hết việc của họ.” Điều nào gần nhất?',s:'Khác biệt giữa chủ động giúp đỡ và ôm hết công việc.',c:['Đúng. Vì đồng đội, nên dù tăng tải công việc của mình cũng phải làm hết.','Về cơ bản đúng. Giúp đỡ nghĩa là hoàn thành nhanh.','Chưa hẳn. Giúp đỡ có thể là hỗ trợ để người đó tự tiến lên hoặc kết nối họ với đúng người và thông tin.','Sai. Không nên liên quan đến việc của đồng nghiệp, chỉ làm phần việc của mình.'],e:'Giúp đồng đội không có nghĩa là làm thay tất cả. Điều quan trọng là hỗ trợ để họ tự tiến lên và kết nối họ với người, thông tin cần thiết.'},
      {q:'Một người nói: “Phải dũng cảm thách thức tiền lệ”, rồi tự ý thay đổi lớn quy trình hiện tại mà không kiểm tra gì. Điều nào phù hợp nhất?',s:'“Thử thách” và “tự ý thay đổi” không giống nhau.',c:['Đúng. Chỉ cần thử điều mới là đã phù hợp với Credo.','Đúng. Vì cần nghi ngờ tiền lệ nên không cần xác nhận.','Chưa hẳn. Nghi ngờ tiền lệ là quan trọng, nhưng cần hiểu lý do và đối thoại để nghĩ ra cách tốt hơn.','Sai. Về cơ bản không nên thay đổi tiền lệ.'],e:'Điểm quan trọng là trân trọng tiền lệ, đặt câu hỏi và đối thoại hướng tới tương lai. Không thay đổi chỉ vì đó là điều mới; hãy hành động để tốt hơn.'},
      {q:'Một nhân viên dạy bí quyết công việc cho hậu bối nhưng nghĩ: “Nếu dạy hết thì mình mất giá trị, nên không dạy các mẹo quan trọng.” Điều nào gần nhất?',s:'Khác biệt giữa “truyền đạt” và “chỉ giữ cho mình”.',c:['Không vấn đề gì. Bảo vệ giá trị của bản thân cũng quan trọng.','Chỉ chia sẻ phần cơ bản là đủ.','Quan trọng là truyền đạt bí quyết và kinh nghiệm để người tiếp theo có thể sử dụng, từ đó nối tiếp giá trị của công việc.','Hậu bối nên tự suy nghĩ nên ngay cả phần cơ bản cũng không cần dạy.'],e:'Điều quan trọng là xây dựng văn hóa truyền đạt và chia sẻ thông tin, chuyển thế mạnh của Hogetsu từ “có” thành “dùng được”.'},
      {q:'Trong 4 hành động sau, hành động nào nhìn có vẻ tốt nhưng thực tế lệch khỏi Credo?',s:'Hãy so sánh 4 hành động.',c:['Lắng nghe yêu cầu khách hàng, xác nhận bối cảnh rồi đề xuất.','Làm hết việc của một hậu bối đang bận và kết thúc mà không để họ làm gì.','Xác nhận vì sao quy trình kém hiệu quả tồn tại và cùng mọi người bàn cách cải tiến.','Biến phương pháp hữu ích mình tìm ra thành quy trình và chia sẻ cho hậu bối.'],e:'B nhìn có vẻ tử tế nhưng hỗ trợ đồng đội không đồng nghĩa với việc lấy hết công việc của họ. Mục tiêu là hỗ trợ và kết nối để họ có thể tự tiến lên.'},
      {q:'Một hậu bối lần đầu phụ trách công việc và đang gặp khó khăn. Bạn vừa cùng làm vừa nói: “Ở đây nên suy nghĩ như thế này” và “Trường hợp này nên hỏi người này”. Điều nào gần nhất?',s:'Bạn đang giúp đồng đội ngay lúc này hay để lại kinh nghiệm?',c:['Mối gắn kết được xây dựng cùng đồng đội','Biến niềm tự hào trong công việc và bí quyết thành giá trị','Năng lực khác biệt','Lấy khách hàng làm trọng tâm'],e:'Trọng tâm là chủ động giúp đỡ đồng đội đang gặp khó khăn và cùng tiến lên. Nếu đồng thời truyền đạt bí quyết thì cũng liên quan đến việc biến bí quyết thành giá trị.'},
      {q:'Khi bàn giao tài liệu cho đồng nghiệp ở công đoạn tiếp theo, bạn sắp xếp và nói: “Xem theo thứ tự này sẽ dễ hiểu; chỗ này cần chú ý.” Điều nào gần nhất?',s:'Người ở công đoạn tiếp theo cũng có thể được xem là “khách hàng”.',c:['Lấy khách hàng làm trọng tâm','Mối gắn kết được xây dựng cùng đồng đội','Năng lực khác biệt','Hài hòa với xã hội'],e:'Người ở công đoạn sau có thể được xem là khách hàng gián tiếp. Ở đây trọng tâm là bàn giao thông tin ở trạng thái tạo giá trị cho người nhận, nên Lấy khách hàng làm trọng tâm là chính.'},
      {q:'Sau nhiều năm làm một công việc, bạn bàn giao cho hậu bối. Bạn muốn truyền đạt không chỉ quy trình mà cả lý do và những sai sót trong quá khứ để họ tự quyết định sau này. Điều nào trực tiếp nhất?',s:'Bàn giao kinh nghiệm và kiến thức.',c:['Mối gắn kết được xây dựng cùng đồng đội','Biến niềm tự hào trong công việc và bí quyết thành giá trị','Lấy khách hàng làm trọng tâm','Năng lực khác biệt'],e:'Trọng tâm là để lại kiến thức, kinh nghiệm và sai sót trong quá khứ như giá trị hữu ích cho người tiếp theo, không chỉ giúp họ trong khoảnh khắc hiện tại.'},
      {q:'Bạn tìm ra một cách làm mới và nghĩ: “Hãy tổng hợp lại để các bộ phận khác cũng có thể dùng.” Điều gì là trọng tâm hơn?',s:'Khác biệt giữa tạo ra phương pháp mới và lưu lại ở dạng có thể sử dụng.',c:['Năng lực khác biệt','Biến niềm tự hào trong công việc và bí quyết thành giá trị','Mối gắn kết được xây dựng cùng đồng đội','Lấy khách hàng làm trọng tâm'],e:'Việc tạo ra cách mới là Năng lực khác biệt, nhưng ở đây hành động chính là tổng hợp để bộ phận khác có thể sử dụng, nên việc biến bí quyết thành giá trị trực tiếp hơn.'},
      {q:'Một hậu bối hỏi: “Tại sao lại làm như vậy?” Sau khi hướng dẫn quy trình, bạn giải thích: “Trước đây đã từng có sai sót này nên chọn cách này để phòng tránh,” và chia sẻ cả bối cảnh. Credo nào thể hiện mạnh nhất?',s:'Không chỉ để lại phương pháp, mà cả kinh nghiệm phía sau.',c:['Năng lực khác biệt','Mối gắn kết được xây dựng cùng đồng đội','Biến niềm tự hào trong công việc và bí quyết thành giá trị','Lấy khách hàng làm trọng tâm'],e:'Điểm chính không phải chỉ là tạo ra phương pháp mới mà là chia sẻ vì sao phương pháp tồn tại cùng kinh nghiệm và sai sót trong quá khứ để người sau sử dụng được. Đây là việc biến bí quyết thành giá trị.'},
      {q:'Sau khi tạo công cụ cải tiến công việc, bạn nghĩ: “Hãy làm tài liệu hướng dẫn để mọi người dễ dùng. Không chỉ ghi cách thao tác mà còn để lại vấn đề cần giải quyết và lý do chọn các thông số này.” Credo nào là trung tâm?',s:'Tập trung vào việc để lại “tại sao”, không chỉ việc đã tạo ra nó.',c:['Năng lực khác biệt','Mối gắn kết được xây dựng cùng đồng đội','Biến niềm tự hào trong công việc và bí quyết thành giá trị','Lấy khách hàng làm trọng tâm'],e:'Bản thân việc tạo công cụ có liên quan đến Năng lực khác biệt, nhưng trọng tâm là để lại vấn đề và bối cảnh phía sau quyết định để người dùng sau này có thể biến kinh nghiệm và phán đoán đó thành giá trị.'}
    ]
  }
};

const UI = {
  en:{
    '抱月クレドクイズ':'Hogetsu Credo Quiz','QUEST START':'QUEST START','クイズで学ぶ、':'Learn through quizzes,','私たちのクレド。':'our Credo.','1分だけ、クレドに触れてみよう。今日のクエストから気軽にスタート。':'Take one minute to explore the Credo. Start with today’s quest.',
    '今日のクエストを読み込み中…':'Loading today’s quest…','はじめる':'Start','クレドを知る':'Learn the Credo','ランキング':'Ranking','ポイント履歴':'Point History','よくある質問':'FAQ','クエストマップを見る':'Quest Map',
    'ホーム':'Home','クイズ':'Quiz','マイページ':'My Page','クレドクエスト 総合ランキング':'Credo Quest Overall Ranking','参加＋正解＋BOSSクリアで貯めたポイントを表示':'Points earned from participation, correct answers, and BOSS clears',
    '累計ポイント':'Total Points','参加回数':'Attempts','最高COMBO':'Best Combo','登録クイズ':'Questions','あなたのクレドクエスト':'Your Credo Quest','クレド見習い':'Credo Trainee','クレドハンター':'Credo Hunter','クレド探検家':'Credo Explorer',
    'アカウント設定':'Account Settings','アカウントをつくる':'Create an Account','ランキングに参加するにはアカウント登録が必要です。ゲーム内の表示名だけをランキングに表示します。':'An account is required to join the ranking. Only your display name is shown in the game.',
    '表示名':'Display Name','ランキングに表示する名前':'Name shown in ranking','メールアドレス':'Email Address','パスワード':'Password','アカウントを登録する':'Create Account','今はデモモードで試す':'Try Demo Mode',
    'パスワードを再設定する':'Reset Password','ログアウト':'Log Out','新規登録':'Sign Up','ログイン':'Log In','言語設定':'Language','日本語':'日本語','Tiếng Việt':'Tiếng Việt','メニュー':'Menu',
    '今日のクエスト':'Today’s Quest','アカウント':'Account','ホームへ戻る':'Back Home','ランキングを見る':'View Ranking','クエストマップ':'Quest Map','閉じる':'Close',
    'FINAL QUEST':'FINAL QUEST','BOSS BATTLE':'BOSS BATTLE','ここまでのクレドを組み合わせて、最後の判断を突破しよう。':'Combine what you have learned and clear the final decision.','剣と盾を持ったBOSS':'BOSS with sword and shield','BOSS EQUIPMENT':'BOSS EQUIPMENT','BOSS HP':'BOSS HP',
    '超上級':'Expert','納期直前、前工程から届いたデータに不備が見つかった。修正すると納期に影響する可能性もある。あなたなら、まずどう動く？':'Just before the deadline, you find an error in data from the previous process. Fixing it may affect the deadline. What do you do first?',
    'A. 自分の判断で修正して、そのまま進める':'A. Fix it yourself and keep going.','B. 影響範囲を整理し、関係者と確認して次の判断につなげる':'B. Assess the impact, confirm with the people involved, and connect it to the next decision.','C. 問題が大きくなるまで保留する':'C. Put it on hold until the problem becomes bigger.','D. すべて前工程に戻して任せる':'D. Send everything back to the previous process.',
    'もう一度考えてみよう。':'Think about it once more.','状況・影響・関係者を整理して次の判断につなげる。複数のクレドを組み合わせた判断です。':'Assess the situation, impact, and people involved, then connect them to the next decision. This combines several Credo ideas.',
    '「自分だけで抱えず、次の判断につなぐ」視点がポイントです。':'The key is to avoid carrying the issue alone and connect it to the next decision.','討伐結果を見る':'See Quest Result','おつかれさまでした！':'Great work!','クレドをクイズで学んでくれてありがとうございます！':'Thank you for learning the Credo through quizzes!','今回の獲得ポイント':'Points Earned This Quest','正解数':'Correct Answers','次へ　›':'Next ›','BOSSへ進む':'Go to BOSS ›','今回：参加 ':'This quest: Participation ','pt ＋ 正解 ':' pt + Correct ',' ＋ BOSS ':' + BOSS ','今回は追加ポイントなし':'No additional points this time',
    'LEARN THE CREDO':'LEARN THE CREDO','抱月クレドを知る':'Learn the Hogetsu Credo','ゲームで出てきたクレドを、公式ページの全文・全体像で確認できます。':'Review the full official Credo page and its overall picture.', '公式サイトを別タブで開く ↗':'Open Official Site ↗',
    'STAGE 01':'STAGE 01','まずはSTAGE 01。クリアが次のクエストへの扉を開きます。':'Start with STAGE 01. Clearing it opens the door to the next quest.',
    'クレドを学ぶ':'Learn the Credo','毎日のクエストで出会ったクレドを、公式ページでも確認できます。ホームの「クレドを知る」から見られます。':'You can also review Credo ideas from each daily quest on the official page. Open it from “Learn the Credo.”'
  },
  vi:{
    '抱月クレドクイズ':'Quiz Credo Hogetsu','QUEST START':'BẮT ĐẦU NHIỆM VỤ','クイズで学ぶ、':'Học qua câu đố,','私たちのクレド。':'Credo của chúng ta.','1分だけ、クレドに触れてみよう。今日のクエストから気軽にスタート。':'Dành 1 phút để tìm hiểu Credo. Hãy bắt đầu với nhiệm vụ hôm nay.',
    '今日のクエストを読み込み中…':'Đang tải nhiệm vụ hôm nay…','はじめる':'Bắt đầu','クレドを知る':'Tìm hiểu Credo','ランキング':'Xếp hạng','ポイント履歴':'Lịch sử điểm','よくある質問':'Câu hỏi thường gặp','クエストマップを見る':'Bản đồ nhiệm vụ',
    'ホーム':'Trang chủ','クイズ':'Câu đố','マイページ':'Trang cá nhân','クレドクエスト 総合ランキング':'Xếp hạng tổng Credo Quest','参加＋正解＋BOSSクリアで貯めたポイントを表示':'Hiển thị điểm tích lũy từ tham gia, trả lời đúng và hạ BOSS',
    '累計ポイント':'Tổng điểm','参加回数':'Số lần tham gia','最高COMBO':'Combo cao nhất','登録クイズ':'Số câu hỏi','あなたのクレドクエスト':'Credo Quest của bạn','クレド見習い':'Người học Credo','クレドハンター':'Thợ săn Credo','クレド探検家':'Nhà thám hiểm Credo',
    'アカウント設定':'Cài đặt tài khoản','アカウントをつくる':'Tạo tài khoản','ランキングに参加するにはアカウント登録が必要です。ゲーム内の表示名だけをランキングに表示します。':'Cần có tài khoản để tham gia xếp hạng. Chỉ tên hiển thị được dùng trên bảng xếp hạng.',
    '表示名':'Tên hiển thị','ランキングに表示する名前':'Tên hiển thị trên xếp hạng','メールアドレス':'Địa chỉ email','パスワード':'Mật khẩu','アカウントを登録する':'Tạo tài khoản','今はデモモードで試す':'Thử chế độ demo',
    'パスワードを再設定する':'Đặt lại mật khẩu','ログアウト':'Đăng xuất','新規登録':'Đăng ký','ログイン':'Đăng nhập','言語設定':'Ngôn ngữ','日本語':'日本語','Tiếng Việt':'Tiếng Việt','メニュー':'Menu',
    '今日のクエスト':'Nhiệm vụ hôm nay','アカウント':'Tài khoản','ホームへ戻る':'Về trang chủ','ランキングを見る':'Xem xếp hạng','クエストマップ':'Bản đồ nhiệm vụ','閉じる':'Đóng',
    'FINAL QUEST':'NHIỆM VỤ CUỐI','BOSS BATTLE':'TRẬN CHIẾN BOSS','ここまでのクレドを組み合わせて、最後の判断を突破しよう。':'Kết hợp những gì đã học để vượt qua quyết định cuối cùng.','剣と盾を持ったBOSS':'BOSS cầm kiếm và khiên','BOSS EQUIPMENT':'TRANG BỊ BOSS','BOSS HP':'HP BOSS',
    '納期直前、前工程から届いたデータに不備が見つかった。修正すると納期に影響する可能性もある。あなたなら、まずどう動く？':'Ngay trước hạn giao, bạn phát hiện dữ liệu từ công đoạn trước có lỗi. Sửa lỗi có thể ảnh hưởng tiến độ. Bạn sẽ làm gì trước?',
    'A. 自分の判断で修正して、そのまま進める':'A. Tự sửa theo判断 của mình và tiếp tục.','B. 影響範囲を整理し、関係者と確認して次の判断につなげる':'B. Xác định phạm vi ảnh hưởng, xác nhận với người liên quan và kết nối với quyết định tiếp theo.','C. 問題が大きくなるまで保留する':'C. Tạm để đó đến khi vấn đề lớn hơn.','D. すべて前工程に戻して任せる':'D. Trả toàn bộ về công đoạn trước và giao họ xử lý.',
    'もう一度考えてみよう。':'Hãy suy nghĩ thêm một lần nữa.','状況・影響・関係者を整理して次の判断につなげる。複数のクレドを組み合わせた判断です。':'Xác định tình huống, ảnh hưởng và người liên quan để kết nối với quyết định tiếp theo. Đây là cách kết hợp nhiều Credo.',
    '「自分だけで抱えず、次の判断につなぐ」視点がポイントです。':'Điểm chính là không ôm vấn đề một mình mà kết nối với quyết định tiếp theo.','討伐結果を見る':'Xem kết quả nhiệm vụ','おつかれさまでした！':'Bạn đã làm rất tốt!','クレドをクイズで学んでくれてありがとうございます！':'Cảm ơn bạn đã học Credo qua các câu đố!','今回の獲得ポイント':'Điểm nhận được lần này','正解数':'Số câu đúng','次へ　›':'Tiếp theo ›','BOSSへ進む':'Đến BOSS ›','今回は追加ポイントなし':'Lần này không có điểm cộng thêm',
    'LEARN THE CREDO':'TÌM HIỂU CREDO','抱月クレドを知る':'Tìm hiểu Credo Hogetsu','ゲームで出てきたクレドを、公式ページの全文・全体像で確認できます。':'Bạn có thể xem toàn bộ Credo chính thức và bức tranh tổng thể.', '公式サイトを別タブで開く ↗':'Mở trang chính thức ↗',
    'まずはSTAGE 01。クリアが次のクエストへの扉を開きます。':'Bắt đầu với STAGE 01. Vượt qua sẽ mở cánh cửa đến nhiệm vụ tiếp theo.',
    'クレドを学ぶ':'Học Credo','毎日のクエストで出会ったクレドを、公式ページでも確認できます。ホームの「クレドを知る」から見られます。':'Bạn có thể xem lại các Credo gặp trong nhiệm vụ hằng ngày trên trang chính thức. Mở từ “Tìm hiểu Credo.”'
  }
};

function lang(){return localStorage.getItem('kredoLanguage')||'ja'}
function trText(v,l){const m=UI[l]||{};return Object.prototype.hasOwnProperty.call(m,v)?m[v]:v}
function tq(q,index,l){
  if(l==='ja')return q;
  const t=CREDO_TRANSLATIONS[l]?.q?.[questions.indexOf(q)];
  if(!t)return q;
  return {level:CREDO_TRANSLATIONS[l].levels[q.level]||q.level,chapter:CREDO_TRANSLATIONS[l].chapters[q.chapter]||q.chapter,question:t.q,scene:t.s,art:q.art,choices:t.c,answer:q.answer,explain:t.e,credo:CREDO_TRANSLATIONS[l].credo[q.credo]||q.credo}
}
function replaceTextNodes(root,l){
  const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);
  const nodes=[];let n;while(n=walker.nextNode())nodes.push(n);
  nodes.forEach(node=>{
    const raw=node.nodeValue;
    const trimmed=raw.trim();
    if(!trimmed||node.parentElement?.closest('iframe,script,style,textarea'))return;
    const translated=trText(trimmed,l);
    if(translated!==trimmed)node.nodeValue=raw.replace(trimmed,translated);
  });
}
function applyStaticUI(){
  const l=lang();
  replaceTextNodes(document.body,l);
  const current=document.getElementById('languageMenuCurrent');if(current)current.textContent=l==='en'?'English':l==='vi'?'Tiếng Việt':'日本語';
  const nav=document.querySelectorAll('.nav-item');const navText=l==='en'?['Home','Quiz','My Page','Ranking']:l==='vi'?['Trang chủ','Câu đố','Trang cá nhân','Xếp hạng']:['ホーム','クイズ','マイページ','ランキング'];
  nav.forEach((b,i)=>{const icon=b.querySelector('.nav-icon');if(icon){[...b.childNodes].filter(x=>x.nodeType===3).forEach(x=>x.remove());b.appendChild(document.createTextNode(navText[i]))}});
  const next=document.getElementById('nextBtn');if(next&&next.style.display!=='none'){const last=typeof current!=='undefined'&&typeof questQuestions!=='undefined'&&current===questQuestions.length-1;next.textContent=l==='en'?(last?'Go to BOSS ›':'Next ›'):l==='vi'?(last?'Đến BOSS ›':'Tiếp theo ›'):(last?'BOSSへ進む':'次へ　›')}
}
function applyQuizTranslation(){
  const l=lang();if(l==='ja')return;
  const q=questQuestions[current];if(!q)return;
  const t=CREDO_TRANSLATIONS[l].q[questions.indexOf(q)];if(!t)return;
  document.getElementById('qCount').textContent=(current+1)+' / '+(questQuestions.length+1);
  document.getElementById('levelTag').textContent=CREDO_TRANSLATIONS[l].levels[q.level]||q.level;
  document.getElementById('chapter').textContent=CREDO_TRANSLATIONS[l].chapters[q.chapter]||q.chapter;
  document.getElementById('question').textContent=t.q;
  document.getElementById('sceneLabel').textContent=l==='en'?'SCENE':'TÌNH HUỐNG';
  document.getElementById('sceneText').textContent=t.s;
  const buttons=document.querySelectorAll('#choices .choice');buttons.forEach((b,i)=>{const span=b.querySelector('span:last-child');if(span)span.textContent=t.c[i]});
  const fb=document.getElementById('feedbackText');const credo=document.getElementById('credoText');
  if(fb&&fb.textContent){const bad=fb.classList.contains('bad')||document.getElementById('feedbackTitle').textContent.includes('🤔');fb.textContent=t.e;credo.textContent=CREDO_TRANSLATIONS[l].credo[q.credo]||q.credo;const ft=document.getElementById('feedbackTitle');if(ft)ft.textContent=bad?(l==='en'?'🤔 Key point':'🤔 Điểm quan trọng'):(l==='en'?'✅ Correct!':'✅ Chính xác!')}
  const nb=document.getElementById('nextBtn');if(nb&&nb.style.display!=='none')nb.textContent=current===questQuestions.length-1?(l==='en'?'Go to BOSS ›':'Đến BOSS ›'):(l==='en'?'Next ›':'Tiếp theo ›');
}
function applyBossTranslation(){
  const l=lang();if(l==='ja')return;
  const m=UI[l]||{};
  const banner=document.querySelector('.boss-banner');if(!banner)return;
  const h=document.querySelector('.boss-title'),sub=document.querySelector('.boss-sub');
  if(h)h.textContent='👑 '+(l==='en'?'BOSS BATTLE':'TRẬN CHIẾN BOSS');
  if(sub)sub.textContent=m['ここまでのクレドを組み合わせて、最後の判断を突破しよう。'];
  const note=document.querySelectorAll('.boss-equipment-note');if(note[0])note[0].textContent=m['剣と盾を持ったBOSS'];if(note[1])note[1].textContent=m['BOSS EQUIPMENT'];
  document.querySelectorAll('.boss-option').forEach(b=>{const txt=b.textContent.trim();if(m[txt])b.textContent=m[txt]});
  const q=document.querySelector('.boss-q h3');if(q)q.textContent=m['納期直前、前工程から届いたデータに不備が見つかった。修正すると納期に影響する可能性もある。あなたなら、まずどう動く？'];
  const clear=document.getElementById('bossClear');if(clear)clear.textContent=m['討伐結果を見る']|| (l==='en'?'See Quest Result':'Xem kết quả nhiệm vụ');
  const result=document.getElementById('bossResult');
  if(result&&result.style.display!=='none'){result.innerHTML=bossDone?(l==='en'?'<strong>⚔ PERFECT!</strong><br>Assess the situation, impact, and people involved, then connect them to the next decision. This combines several Credo ideas.':'<strong>⚔ HOÀN HẢO!</strong><br>Xác định tình huống, ảnh hưởng và người liên quan để kết nối với quyết định tiếp theo. Đây là cách kết hợp nhiều Credo.'):(l==='en'?'<strong>Think about it once more.</strong><br>The key is to avoid carrying the issue alone and connect it to the next decision.':'<strong>Hãy suy nghĩ thêm một lần nữa.</strong><br>Điểm chính là không ôm vấn đề một mình mà kết nối với quyết định tiếp theo.')}
}
function saveLanguageMeta(){document.documentElement.lang=lang()==='ja'?'ja':lang()==='en'?'en':'vi'}
function setLanguageReal(l){
  if(!CREDO_TRANSLATIONS[l]&&l!=='ja')return;
  localStorage.setItem('kredoLanguage',l);saveLanguageMeta();
  applyStaticUI();applyQuizTranslation();applyBossTranslation();applyResultTranslation();
  if(window.closeLanguageSettings)window.closeLanguageSettings();
  showToast('🌐 '+(l==='en'?'English':l==='vi'?'Tiếng Việt':'日本語')+' selected');
}
function translateDynamic(){
  applyStaticUI();
  if(document.getElementById('quiz')?.classList.contains('active'))applyQuizTranslation();
  if(document.getElementById('boss')?.classList.contains('active'))applyBossTranslation();
  if(document.getElementById('result')?.classList.contains('active'))applyResultTranslation();
}
function applyResultTranslation(){
  const l=lang();if(l==='ja')return;const m=UI[l]||{};
  const label=document.querySelector('.result-label');if(label)label.textContent=m['今回の獲得ポイント']||label.textContent;
  const thanks=document.querySelector('.thanks');if(thanks)thanks.innerHTML=(l==='en'?'Great work!<br>Thank you for learning the Credo through quizzes!':'Bạn đã làm rất tốt!<br>Cảm ơn bạn đã học Credo qua các câu đố!');
  const stats=document.querySelectorAll('.rstat small');if(stats[0])stats[0].textContent=l==='en'?'Correct Answers':'Số câu đúng';if(stats[1])stats[1].textContent=l==='en'?'Best Combo':'Combo cao nhất';
}
const origShow=window.show;
window.show=function(id){origShow(id);setTimeout(()=>{applyStaticUI();if(id==='quiz')applyQuizTranslation();if(id==='boss')applyBossTranslation();if(id==='result')applyResultTranslation()},0)};
const origRenderQuestion=window.renderQuestion;
window.renderQuestion=function(){origRenderQuestion();applyQuizTranslation()};
const origAnswer=window.answer;
window.answer=function(i){origAnswer(i);applyQuizTranslation()};
const origBossAnswer=window.bossAnswer;
window.bossAnswer=function(btn,good){origBossAnswer(btn,good);applyBossTranslation()};
const origRenderRanking=window.renderRanking;
window.renderRanking=async function(){const r=await origRenderRanking();applyStaticUI();return r};
const origUpdateProfile=window.updateProfile;
window.updateProfile=function(){origUpdateProfile();applyStaticUI()};
window.setLanguage=setLanguageReal;
document.documentElement.lang=lang()==='ja'?'ja':lang();
setTimeout(()=>{applyStaticUI();applyQuizTranslation();applyBossTranslation();applyResultTranslation()},0);
})();