-- クレドクエスト本番用 Supabase schema
-- 既存構成を壊さず再実行できるように作成しています。

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'プレイヤー',
  total_points integer not null default 0,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "profiles_select_public" on public.profiles;
create policy "profiles_select_public"
on public.profiles for select
using (true);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles for insert
with check (auth.uid() = id);

drop policy if exists "profiles_update_own_display_name" on public.profiles;
create policy "profiles_update_own_display_name"
on public.profiles for update
using (auth.uid() = id)
with check (auth.uid() = id);

-- クライアントからポイントを直接変更できないように列権限を制限。
revoke update on public.profiles from anon, authenticated;
grant update(display_name) on public.profiles to authenticated;
revoke insert on public.profiles from anon, authenticated;
grant insert(id, display_name) on public.profiles to authenticated;

create table if not exists public.quiz_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  quest_date date not null,
  correct_count integer not null default 0,
  total_questions integer not null default 0,
  boss_cleared boolean not null default false,
  points integer not null default 0,
  completed_at timestamptz not null default now()
);

alter table public.quiz_attempts enable row level security;

drop policy if exists "attempts_insert_own" on public.quiz_attempts;
drop policy if exists "attempts_select_own" on public.quiz_attempts;

-- 参加履歴の追加はRPCだけに限定する。
create policy "attempts_select_own"
on public.quiz_attempts for select
using (auth.uid() = user_id);

revoke insert, update, delete on public.quiz_attempts from anon, authenticated;
grant select on public.quiz_attempts to authenticated;

create unique index if not exists quiz_attempts_daily_unique
on public.quiz_attempts(user_id, quest_date);

-- 参加・正解・BOSSのポイントをサーバー側で計算して記録。
-- 同日2回目は記録せず、points=0を返す。
create or replace function public.record_quest_attempt(
  p_quest_date date,
  p_correct_count integer,
  p_total_questions integer,
  p_boss_cleared boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  earned integer;
  inserted_id bigint;
begin
  if uid is null then
    raise exception 'not authenticated';
  end if;

  if p_total_questions <= 0
     or p_correct_count < 0
     or p_correct_count > p_total_questions then
    raise exception 'invalid quest result';
  end if;

  earned := 10 + (p_correct_count * 2) + case when p_boss_cleared then 5 else 0 end;

  insert into public.quiz_attempts(
    user_id, quest_date, correct_count, total_questions, boss_cleared, points
  )
  values (
    uid, p_quest_date, p_correct_count, p_total_questions, p_boss_cleared, earned
  )
  on conflict (user_id, quest_date) do nothing
  returning id into inserted_id;

  if inserted_id is null then
    return jsonb_build_object(
      'recorded', false,
      'points', 0
    );
  end if;

  update public.profiles
  set total_points = total_points + earned,
      updated_at = now()
  where id = uid;

  return jsonb_build_object(
    'recorded', true,
    'points', earned
  );
end;
$$;

revoke all on function public.record_quest_attempt(date, integer, integer, boolean) from public;
grant execute on function public.record_quest_attempt(date, integer, integer, boolean) to authenticated;

-- ランキング表示用ビュー
create or replace view public.monthly_ranking as
select
  p.id,
  p.display_name,
  p.total_points,
  p.updated_at
from public.profiles p
order by p.total_points desc, p.updated_at asc;
