-- クレドクエスト 管理者機能セットアップ
-- Supabase の SQL Editor でこのファイルを実行してください。
-- 管理者は kredo_admins に登録された auth.users のみです。
-- クライアントに service_role key を置かず、更新処理は権限確認付き RPC 経由で実行します。

begin;

create table if not exists public.kredo_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.kredo_admins enable row level security;
revoke all on table public.kredo_admins from public, anon, authenticated;

create table if not exists public.kredo_admin_point_adjustments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  admin_user_id uuid references auth.users(id) on delete set null,
  points_added integer not null check (points_added > 0),
  balance_after bigint not null,
  reason text not null check (length(trim(reason)) >= 2),
  created_at timestamptz not null default now()
);

create index if not exists kredo_admin_point_adjustments_created_at_idx
  on public.kredo_admin_point_adjustments (created_at desc);
create index if not exists kredo_admin_point_adjustments_user_id_idx
  on public.kredo_admin_point_adjustments (user_id, created_at desc);

alter table public.kredo_admin_point_adjustments enable row level security;
revoke all on table public.kredo_admin_point_adjustments from public, anon, authenticated;
grant usage on schema public to authenticated;


create table if not exists public.kredo_reward_redemptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  reward_id text not null,
  reward_name text not null,
  points_spent integer not null check (points_spent > 0),
  balance_after bigint not null check (balance_after >= 0),
  redeemed_at timestamptz not null default now()
);

create index if not exists kredo_reward_redemptions_redeemed_at_idx
  on public.kredo_reward_redemptions (redeemed_at desc);
create index if not exists kredo_reward_redemptions_user_id_idx
  on public.kredo_reward_redemptions (user_id, redeemed_at desc);

alter table public.kredo_reward_redemptions enable row level security;
revoke all on table public.kredo_reward_redemptions from public, anon, authenticated;

create or replace function public.kredo_admin_is_authorized()
returns boolean
language sql
stable
security definer
set search_path = ''
as $function$
  select exists (
    select 1
    from public.kredo_admins a
    where a.user_id = auth.uid()
  );
$function$;

create or replace function public.kredo_admin_dashboard()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if auth.uid() is null or not public.kredo_admin_is_authorized() then
    raise exception 'admin_access_required' using errcode = '42501';
  end if;

  return jsonb_build_object(
    'users', (select count(*) from public.profiles),
    'attempts', (select count(*) from public.quiz_attempts),
    'total_points', (select coalesce(sum(p.total_points), 0) from public.profiles p)
  );
end;
$function$;

create or replace function public.kredo_admin_list_users(
  p_search text default null,
  p_limit integer default 100,
  p_offset integer default 0
)
returns table (
  user_id uuid,
  display_name text,
  email text,
  total_points bigint,
  attempt_count bigint,
  joined_at timestamptz,
  updated_at timestamptz,
  has_profile boolean
)
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_search text := nullif(trim(coalesce(p_search, '')), '');
begin
  if auth.uid() is null or not public.kredo_admin_is_authorized() then
    raise exception 'admin_access_required' using errcode = '42501';
  end if;

  return query
    select
      u.id,
      coalesce(p.display_name, '')::text,
      coalesce(u.email, '')::text,
      coalesce(p.total_points, 0)::bigint,
      coalesce(attempts.count_value, 0)::bigint,
      u.created_at,
      p.updated_at,
      (p.id is not null)
    from auth.users u
    left join public.profiles p on p.id = u.id
    left join lateral (
      select count(*) as count_value
      from public.quiz_attempts qa
      where qa.user_id = u.id
    ) attempts on true
    where v_search is null
      or coalesce(p.display_name, '') ilike '%' || v_search || '%'
      or coalesce(u.email, '') ilike '%' || v_search || '%'
    order by coalesce(p.total_points, 0) desc, u.created_at desc
    limit least(greatest(coalesce(p_limit, 100), 1), 200)
    offset greatest(coalesce(p_offset, 0), 0);
end;
$function$;

create or replace function public.kredo_admin_grant_points(
  p_user_id uuid,
  p_points integer,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_balance bigint;
  v_reason text := trim(coalesce(p_reason, ''));
begin
  if auth.uid() is null or not public.kredo_admin_is_authorized() then
    raise exception 'admin_access_required' using errcode = '42501';
  end if;

  if p_user_id is null then
    raise exception 'target_user_required' using errcode = '22023';
  end if;
  if p_points is null or p_points < 1 or p_points > 5000 then
    raise exception 'points_must_be_between_1_and_5000' using errcode = '22023';
  end if;
  if length(v_reason) < 2 or length(v_reason) > 160 then
    raise exception 'reason_must_be_between_2_and_160_characters' using errcode = '22023';
  end if;

  update public.profiles p
  set total_points =
      greatest(
        coalesce(p.total_points, 0)::bigint,
        coalesce((
          select sum(qa.points)::bigint
          from public.quiz_attempts qa
          where qa.user_id = p_user_id
        ), 0)
      ) + p_points,
      updated_at = now()
  where p.id = p_user_id
  returning p.total_points::bigint into v_balance;

  if not found then
    raise exception 'target_profile_not_found' using errcode = 'P0002';
  end if;

  insert into public.kredo_admin_point_adjustments
    (user_id, admin_user_id, points_added, balance_after, reason)
  values
    (p_user_id, auth.uid(), p_points, v_balance, v_reason);

  return jsonb_build_object(
    'user_id', p_user_id,
    'points_added', p_points,
    'balance_after', v_balance,
    'reason', v_reason
  );
end;
$function$;

create or replace function public.kredo_admin_recent_point_adjustments()
returns table (
  adjustment_id bigint,
  user_id uuid,
  display_name text,
  user_email text,
  points_added integer,
  balance_after bigint,
  reason text,
  admin_email text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if auth.uid() is null or not public.kredo_admin_is_authorized() then
    raise exception 'admin_access_required' using errcode = '42501';
  end if;

  return query
    select
      a.id,
      a.user_id,
      coalesce(p.display_name, '')::text,
      coalesce(u.email, '')::text,
      a.points_added,
      a.balance_after,
      a.reason,
      coalesce(admin_user.email, '')::text,
      a.created_at
    from public.kredo_admin_point_adjustments a
    left join public.profiles p on p.id = a.user_id
    left join auth.users u on u.id = a.user_id
    left join auth.users admin_user on admin_user.id = a.admin_user_id
    order by a.created_at desc
    limit 100;
end;
$function$;


create or replace function public.kredo_redeem_reward(p_reward_id text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_user_id uuid := auth.uid();
  v_cost integer;
  v_reward_name text;
  v_total bigint;
  v_spent bigint;
  v_balance bigint;
  v_redemption_id bigint;
begin
  if v_user_id is null then
    raise exception 'login_required' using errcode = '42501';
  end if;

  -- 景品IDと価格はサーバー側で固定し、クライアントからの価格改変を防ぎます。
  case p_reward_id
    when 'cafe1' then v_cost := 100; v_reward_name := 'ホウゲツカフェから好きな1品券';
    when 'cafe2' then v_cost := 200; v_reward_name := 'ホウゲツカフェ 2人分';
    when 'lottery1' then v_cost := 300; v_reward_name := '抽せん確率アップ権 1個';
    when 'lottery2' then v_cost := 500; v_reward_name := '抽せん確率アップ権 2個';
    else raise exception 'reward_not_available' using errcode = '22023';
  end case;

  -- 同じ利用者の同時交換を直列化し、二重消費を防ぎます。
  select coalesce(p.total_points, 0)::bigint
    into v_total
  from public.profiles p
  where p.id = v_user_id
  for update;

  if not found then
    raise exception 'profile_not_found' using errcode = 'P0002';
  end if;

  select coalesce(pc.spent_points, 0)::bigint
    into v_spent
  from public.player_customizations pc
  where pc.user_id = v_user_id
  for update;

  if not found then
    v_spent := 0;
    insert into public.player_customizations
      (user_id, avatar_config, room_theme, room_items, owned_items, spent_points, updated_at)
    values
      (
        v_user_id,
        jsonb_build_object('hairStyle','short','hairColor','black','outfit','work','accessory','none','effect','none'),
        'basic',
        jsonb_build_array('desk','chair','plant'),
        jsonb_build_object('skins',jsonb_build_array(),'furniture',jsonb_build_array('desk','chair','plant')),
        0,
        now()
      )
    on conflict (user_id) do nothing;

    -- 同じユーザーの別処理が先に行を作った場合も、保存済み残高を読み直します。
    if not found then
      select coalesce(pc.spent_points, 0)::bigint
        into v_spent
      from public.player_customizations pc
      where pc.user_id = v_user_id
      for update;
    end if;
  end if;

  v_balance := v_total - v_spent;
  if v_balance < v_cost then
    raise exception 'insufficient_points' using errcode = 'P0001';
  end if;

  update public.player_customizations pc
     set spent_points = v_spent + v_cost,
         updated_at = now()
   where pc.user_id = v_user_id;

  v_balance := v_total - (v_spent + v_cost);

  insert into public.kredo_reward_redemptions
    (user_id, reward_id, reward_name, points_spent, balance_after)
  values
    (v_user_id, p_reward_id, v_reward_name, v_cost, v_balance)
  returning id into v_redemption_id;

  return jsonb_build_object(
    'redemption_id', v_redemption_id,
    'user_id', v_user_id,
    'reward_id', p_reward_id,
    'reward_name', v_reward_name,
    'points_spent', v_cost,
    'total_points', v_total,
    'spent_points', v_spent + v_cost,
    'balance_after', v_balance
  );
end;
$function$;

create or replace function public.kredo_admin_recent_reward_redemptions()
returns table (
  redemption_id bigint,
  user_id uuid,
  display_name text,
  user_email text,
  reward_name text,
  points_spent integer,
  balance_after bigint,
  redeemed_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if auth.uid() is null or not public.kredo_admin_is_authorized() then
    raise exception 'admin_access_required' using errcode = '42501';
  end if;

  return query
    select
      r.id,
      r.user_id,
      coalesce(p.display_name, '')::text,
      coalesce(u.email, '')::text,
      r.reward_name,
      r.points_spent,
      r.balance_after,
      r.redeemed_at
    from public.kredo_reward_redemptions r
    left join public.profiles p on p.id = r.user_id
    left join auth.users u on u.id = r.user_id
    order by r.redeemed_at desc
    limit 200;
end;
$function$;

revoke all on function public.kredo_redeem_reward(text) from public, anon, authenticated;
revoke all on function public.kredo_admin_recent_reward_redemptions() from public, anon, authenticated;
revoke all on function public.kredo_admin_is_authorized() from public, anon, authenticated;
revoke all on function public.kredo_admin_dashboard() from public, anon, authenticated;
revoke all on function public.kredo_admin_list_users(text, integer, integer) from public, anon, authenticated;
revoke all on function public.kredo_admin_grant_points(uuid, integer, text) from public, anon, authenticated;
revoke all on function public.kredo_admin_recent_point_adjustments() from public, anon, authenticated;

grant execute on function public.kredo_redeem_reward(text) to authenticated;
grant execute on function public.kredo_admin_recent_reward_redemptions() to authenticated;
grant execute on function public.kredo_admin_is_authorized() to authenticated;
grant execute on function public.kredo_admin_dashboard() to authenticated;
grant execute on function public.kredo_admin_list_users(text, integer, integer) to authenticated;
grant execute on function public.kredo_admin_grant_points(uuid, integer, text) to authenticated;
grant execute on function public.kredo_admin_recent_point_adjustments() to authenticated;

notify pgrst, 'reload schema';

commit;

-- 管理者ユーザーの追加は、対象アカウントを通常画面で登録したあとに実行します。
-- 下のメールアドレスを実際の管理者メールに置き換え、コメントを外して実行してください。
-- insert into public.kredo_admins (user_id)
-- select id from auth.users where lower(email) = lower('REPLACE_WITH_ADMIN_EMAIL')
-- on conflict (user_id) do nothing;
